-- ============================================================
-- WordMax Database Schema
-- Run this in Supabase SQL Editor (Dashboard → SQL Editor → New query)
-- ============================================================

-- Enable UUID generation
create extension if not exists "uuid-ossp";

-- ============================================================
-- TABLES
-- ============================================================

-- Words
create table if not exists public.words (
  id          uuid default uuid_generate_v4() primary key,
  user_id     uuid references auth.users(id) on delete cascade not null,
  word        text not null,
  sentence    text,
  context     text,
  created_at  timestamptz default now() not null
);

-- Exercises (generated by AI, stored once per word)
create table if not exists public.exercises (
  id          uuid default uuid_generate_v4() primary key,
  word_id     uuid references public.words(id) on delete cascade not null,
  type        text not null check (type in ('fill_blank', 'usage_scenario', 'sentence_rewrite')),
  question    text not null,
  answer      text not null,
  explanation text not null,
  created_at  timestamptz default now() not null
);

-- Reviews (each time a user marks an exercise correct/incorrect)
create table if not exists public.reviews (
  id           uuid default uuid_generate_v4() primary key,
  word_id      uuid references public.words(id) on delete cascade not null,
  user_id      uuid references auth.users(id) on delete cascade not null,
  correct      boolean not null,
  reviewed_at  timestamptz default now() not null
);

-- Spaced repetition progress per word
create table if not exists public.word_progress (
  id            uuid default uuid_generate_v4() primary key,
  word_id       uuid references public.words(id) on delete cascade not null,
  user_id       uuid references auth.users(id) on delete cascade not null,
  last_reviewed timestamptz,
  next_review   timestamptz default now() not null,
  interval      integer default 1 not null,  -- days until next review
  created_at    timestamptz default now() not null,
  unique (word_id, user_id)
);

-- ============================================================
-- INDEXES
-- ============================================================

create index if not exists words_user_id_idx on public.words(user_id);
create index if not exists words_created_at_idx on public.words(created_at desc);
create index if not exists exercises_word_id_idx on public.exercises(word_id);
create index if not exists reviews_user_id_idx on public.reviews(user_id);
create index if not exists word_progress_user_id_idx on public.word_progress(user_id);
create index if not exists word_progress_next_review_idx on public.word_progress(next_review);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

alter table public.words enable row level security;
alter table public.exercises enable row level security;
alter table public.reviews enable row level security;
alter table public.word_progress enable row level security;

-- Words: users can only access their own words
create policy "words_select_own" on public.words
  for select using (auth.uid() = user_id);

create policy "words_insert_own" on public.words
  for insert with check (auth.uid() = user_id);

create policy "words_delete_own" on public.words
  for delete using (auth.uid() = user_id);

-- Exercises: accessible if the user owns the parent word
create policy "exercises_select_via_word" on public.exercises
  for select using (
    exists (
      select 1 from public.words
      where words.id = exercises.word_id
        and words.user_id = auth.uid()
    )
  );

create policy "exercises_insert_via_word" on public.exercises
  for insert with check (
    exists (
      select 1 from public.words
      where words.id = exercises.word_id
        and words.user_id = auth.uid()
    )
  );

-- Reviews: users can only access their own
create policy "reviews_select_own" on public.reviews
  for select using (auth.uid() = user_id);

create policy "reviews_insert_own" on public.reviews
  for insert with check (auth.uid() = user_id);

-- Word progress: users can only access their own
create policy "word_progress_select_own" on public.word_progress
  for select using (auth.uid() = user_id);

create policy "word_progress_insert_own" on public.word_progress
  for insert with check (auth.uid() = user_id);

create policy "word_progress_update_own" on public.word_progress
  for update using (auth.uid() = user_id);
